// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkVkrDccCrgww0cXuNSnjfaUVxDiWTJE',
    appId: '1:634565118340:web:435fe858851c7676cd35d1',
    messagingSenderId: '634565118340',
    projectId: 'mobileproject-8bdc5',
    authDomain: 'mobileproject-8bdc5.firebaseapp.com',
    storageBucket: 'mobileproject-8bdc5.firebasestorage.app',
    measurementId: 'G-S2RJRTCES7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHmMBkFe8VqaMLJawcxLPjCVAM6t_CcEo',
    appId: '1:634565118340:android:d16a75f745735e2bcd35d1',
    messagingSenderId: '634565118340',
    projectId: 'mobileproject-8bdc5',
    storageBucket: 'mobileproject-8bdc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAGN5d84-H2U-OK82FnyuH6eVqOvzDKDE',
    appId: '1:634565118340:ios:3e08ef465d162e22cd35d1',
    messagingSenderId: '634565118340',
    projectId: 'mobileproject-8bdc5',
    storageBucket: 'mobileproject-8bdc5.firebasestorage.app',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAGN5d84-H2U-OK82FnyuH6eVqOvzDKDE',
    appId: '1:634565118340:ios:3e08ef465d162e22cd35d1',
    messagingSenderId: '634565118340',
    projectId: 'mobileproject-8bdc5',
    storageBucket: 'mobileproject-8bdc5.firebasestorage.app',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwkVkrDccCrgww0cXuNSnjfaUVxDiWTJE',
    appId: '1:634565118340:web:97a568b75d274fa7cd35d1',
    messagingSenderId: '634565118340',
    projectId: 'mobileproject-8bdc5',
    authDomain: 'mobileproject-8bdc5.firebaseapp.com',
    storageBucket: 'mobileproject-8bdc5.firebasestorage.app',
    measurementId: 'G-DR95ZNSNX5',
  );
}
